# Generated by Django 3.2.9 on 2021-11-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teaser", "0002_auto_20150924_0221"),
    ]

    operations = [
        migrations.AddField(
            model_name="filerteaseritem",
            name="url_title",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="URL title"),
        ),
    ]
